import {ethers} from "hardhat";
import {INSTANT_ACTIONS_ADDRESS} from "./contractAddresses";
import {EstforConstants} from "@paintswap/estfor-definitions";
import {allInstantActions} from "./data/instantActions";

async function main() {
  const [owner] = await ethers.getSigners();
  console.log(`Edit instant actions using account: ${owner.address} on chain id ${await owner.getChainId()}`);

  const instantActions = await ethers.getContractAt("InstantActions", INSTANT_ACTIONS_ADDRESS);

  const actionIds = new Set([
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_HELMET_1,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_ARMOR_1,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_TASSETS_1,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_GAUNTLETS_1,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_BOOTS_1,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_SHIELD_1,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_SWORD_1,
    EstforConstants.INSTANT_ACTION_FORGING_DRAGONSTONE_AMULET_1,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_HAT_1,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BODY_1,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_TROUSERS_1,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BRACERS_1,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BOOTS_1,
    EstforConstants.INSTANT_ACTION_FORGING_DRAGONSTONE_STAFF_1,
    EstforConstants.INSTANT_ACTION_FORGING_GODLY_BOW_1,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_COWL_1,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BODY_1,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_CHAPS_1,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BRACERS_1,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BOOTS_1,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_HELMET_2,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_ARMOR_2,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_TASSETS_2,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_GAUNTLETS_2,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_BOOTS_2,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_SHIELD_2,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_SWORD_2,
    EstforConstants.INSTANT_ACTION_FORGING_DRAGONSTONE_AMULET_2,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_HAT_2,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BODY_2,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_TROUSERS_2,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BRACERS_2,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BOOTS_2,
    EstforConstants.INSTANT_ACTION_FORGING_DRAGONSTONE_STAFF_2,
    EstforConstants.INSTANT_ACTION_FORGING_GODLY_BOW_2,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_COWL_2,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BODY_2,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_CHAPS_2,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BRACERS_2,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BOOTS_2,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_HELMET_3,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_ARMOR_3,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_TASSETS_3,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_GAUNTLETS_3,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_BOOTS_3,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_SHIELD_3,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_SWORD_3,
    EstforConstants.INSTANT_ACTION_FORGING_DRAGONSTONE_AMULET_3,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_HAT_3,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BODY_3,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_TROUSERS_3,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BRACERS_3,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BOOTS_3,
    EstforConstants.INSTANT_ACTION_FORGING_DRAGONSTONE_STAFF_3,
    EstforConstants.INSTANT_ACTION_FORGING_GODLY_BOW_3,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_COWL_3,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BODY_3,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_CHAPS_3,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BRACERS_3,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BOOTS_3,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_HELMET_4,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_ARMOR_4,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_TASSETS_4,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_GAUNTLETS_4,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_BOOTS_4,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_SHIELD_4,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_SWORD_4,
    EstforConstants.INSTANT_ACTION_FORGING_DRAGONSTONE_AMULET_4,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_HAT_4,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BODY_4,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_TROUSERS_4,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BRACERS_4,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BOOTS_4,
    EstforConstants.INSTANT_ACTION_FORGING_DRAGONSTONE_STAFF_4,
    EstforConstants.INSTANT_ACTION_FORGING_GODLY_BOW_4,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_COWL_4,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BODY_4,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_CHAPS_4,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BRACERS_4,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BOOTS_4,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_HELMET_5,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_ARMOR_5,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_TASSETS_5,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_GAUNTLETS_5,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_BOOTS_5,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_SHIELD_5,
    EstforConstants.INSTANT_ACTION_FORGING_ORICHALCUM_SWORD_5,
    EstforConstants.INSTANT_ACTION_FORGING_DRAGONSTONE_AMULET_5,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_HAT_5,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BODY_5,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_TROUSERS_5,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BRACERS_5,
    EstforConstants.INSTANT_ACTION_FORGING_MASTER_BOOTS_5,
    EstforConstants.INSTANT_ACTION_FORGING_DRAGONSTONE_STAFF_5,
    EstforConstants.INSTANT_ACTION_FORGING_GODLY_BOW_5,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_COWL_5,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BODY_5,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_CHAPS_5,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BRACERS_5,
    EstforConstants.INSTANT_ACTION_FORGING_SCORCHING_BOOTS_5,
  ]);

  const actions = allInstantActions.filter((action) => {
    if (action) {
      return actionIds.has(action.actionId);
    }
  });

  if (actions.length !== actionIds.size) {
    console.log("Cannot find all instant actions");
  } else {
    await instantActions.editActions(actions);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
