name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: yarn install
        shell: bash
      - name: Create local node and deploy
        run: yarn deploy.ts
      - name: Run Tests
        run: yarn hardhat test
