name: CI
on:
  push:
    branches:
      - main
      - beta
      - sonic
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Foundry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4
      - uses: foundry-rs/foundry-toolchain@v1
      - name: Install packages
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
        shell: bash
      - name: Tests
        run: forge test
